### PR TITLE
Persist request to Dependency Monkey runs

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/storages/pull/2221
Related: https://github.com/thoth-station/adviser/pull/1670

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold


Requires a new thoth-storages release with thoth-station/storages#2221.

**Review by pacospace — APPROVED** [review]
Thanks! 🥇

**Pull request merged**
