### PR TITLE
Adjust parameters supplied to Dependency Monkey scheduling

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/thoth-application/issues/902
Related: https://github.com/thoth-station/thoth-application/pull/912
Depends-On: https://github.com/thoth-station/common/pull/1109

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
lgtm! 👍🏼

**Comment by fridex** [comment]
/hold

This requires thoth-station/common#1109.

**Comment by fridex** [comment]
/unhold
/approve

We have required thoth-common in place.

**Pull request merged**
