### PR TITLE
Expose schema revision

### PR DESCRIPTION
**Pull request by pacospace**
## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/metrics-exporter/issues/529

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Introduce metric to expose revision migration available from thoth-storages library

### CODE REVIEW

**Comment by pacospace** [comment]
Tested in the cluster in test environment

```
# HELP management_api_schema_revision_script Management API database schema revision from script
# TYPE management_api_schema_revision_script gauge
management_api_schema_revision_script{revision="91620576525b"} 0.0
```

**Comment by pacospace** [comment]
> Tested in the cluster in test environment
> 
> ```
> # HELP management_api_schema_revision_script Management API database schema revision from script
> # TYPE management_api_schema_revision_script gauge
> management_api_schema_revision_script{revision="91620576525b"} 0.0
> ```

I think it would be better to use same name for all metrics and specific label, so we can handle it in an easy way from Grafana point of view and for alarms:

`thoth_schema_revision_script{component="management-api", revision="91620576525b"} 0.0`

**Review by fridex — APPROVED** [review]
lgtm, thanks! :+1:

**Pull request merged**
