### PR TITLE
Provide endpoint which exposes all the Python indexes

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
> Build failed.
> 
> * [thoth-coala ](https://managesf.thoth-station.ninja/logs/80/280/5d8e8bdcd0b77ada256c4411ad39f2149fccdb73/check/thoth-coala/c40f6a8/) : FAILURE in 22s

Not relevant.

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
do we want to move this from user-api to management-api?

**Comment by fridex** [comment]
> do we want to move this from user-api to management-api?

User API exposes just enabled ones. Management API exposes enabled and also disabled ones.

**Pull request merged**
