### PR TITLE
Provide force_sync option when scheduling solvers

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/common/pull/1162
Related: https://github.com/thoth-station/storages/issues/2308

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
/hold

until a new release with https://github.com/thoth-station/common/pull/1162 of thoth-common is done.

**Comment by goern** [comment]
@fridex this could be unholded, right?

**Comment by fridex** [comment]
> @fridex this could be unholded, right?

The new thoth-common library that is a dependency of this PR was not released.

**Review by harshad16 — APPROVED** [review]
lgtm
thoth-common is released and available through #784 
/unhold

**Pull request merged**
