### PR TITLE
Update pre-commit base image version

### PR DESCRIPTION
**Pull request by mayaCostantini**
## This introduces a breaking change

- No

### CODE REVIEW

**Comment by mayaCostantini** [comment]
See failing `pre-commit` check: https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_management-api/868/pre-commit/1511670552467607552

**Comment by harshad16** [comment]
can you also check there is any update, by doing: `pre-commit autoupdate`

**Comment by mayaCostantini** [comment]
I ran the command and everything is up to date

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Comment by mayaCostantini** [comment]
@fridex Needs your approval 👍🏻

**Review by fridex — APPROVED** [review]
🥇

**Pull request merged**
